spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vms
    username:
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/master.yaml