spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${VMS_DATASOURCE_URL}
    username: ${VMS_DATASOURCE_USERNAME}
    password: ${VMS_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml